# ------------------------------------------------------------------ #
#               BenthPinata - Ana Yapılandırma Dosyası               #
# ------------------------------------------------------------------ #
#
# Hoş geldiniz! Bu dosyada BenthPinata eklentisinin tüm temel
# ayarlarını bulabilirsiniz. Değişiklik yaparken dikkatli olun.
# YAML formatı boşluklara duyarlıdır. Sekme (TAB) kullanmayın,
# sadece boşluk (space) kullanın.
#
# Bir ayarı ne işe yaradığını anlamak için üstündeki yorumları okuyun.
#
# ------------------------------------------------------------------ #

# ------------------------------------------------------------------ #
#                           Genel Ayarlar                            #
# ------------------------------------------------------------------ #
general:
  # Piñata etkinliğinin başlaması için geri sayım süresi (saniye olarak).
  countdown-time: 15

  # Piñata'ya bir oyuncunun art arda ne kadar hızlı vurabileceğini belirler (milisaniye).
  # Spam ve lag'ı önlemek için kullanılır. 500 = saniyede 2 vuruş.
  hit-cooldown-millis: 500

  # Eğer bir Piñata türü için özel can değeri belirtilmezse,
  # varsayılan olarak kullanılacak can değeri.
  default-pinata-health: 100


# ------------------------------------------------------------------ #
#                      Piñata Türleri Ayarları                       #
# ------------------------------------------------------------------ #
#
# Burada istediğiniz kadar farklı Piñata türü oluşturabilirsiniz.
# Her türün kendine özgü konumu, canı, görünüşü ve diğer özellikleri olabilir.
# Komut: /pinata start <tür_adı>
#
pinata-types:
  # Bu, 'default' ismindeki Piñata türüdür. Geriye dönük uyumluluk için
  # 'entity-type' belirtilmediğinde KOYUN olarak doğar.
  default:
    spawn-location: 'world;0;100;0'
    health: 150

  # Bu, 'zindan' isminde bir Zombi Piñata türüdür.
  zindan:
    spawn-location: 'world;15;70;25'
    health: 250
    entity-type: 'ZOMBIE'
    mob-options:
      is-baby: false
      glowing: true
      custom-name: '&4&lZİNDAN PİÑATASI'
      custom-name-visible: true
      # NBT verisi enjekte ediyoruz. Formatın geçerli bir JSON/NBT olduğundan emin olun!
      # Yaygın etiketler: { "Silent": 1b }, { "NoAI": 1b }, { "Invulnerable": 1b }
      nbt-data: '{ "Silent": 1b, "NoAI": 1b }'

  # Bu, 'tüccar' isminde, mor halılı ve özel bir Lamadır.
  tuccar:
    spawn-location: 'dungeon;150;64;-200'
    health: 100
    entity-type: 'LLAMA'
    mob-options:
      custom-name: '&e&lGezgin Tüccar Piñata'
      glowing: false
      # Llama'ya özel seçenekler
      llama-color: 'CREAMY'      # Renkler: CREAMY, WHITE, BROWN, GRAY
      carpet-color: 'PURPLE'   # Herhangi bir yün rengi (örn: BLUE, RED...)

  # At Piñata örneği
  pegasus:
    spawn-location: 'world;0;100;0'
    health: 300
    entity-type: 'HORSE'
    mob-options:
      glowing: true
      horse-color: 'WHITE' # Renkler: WHITE, CREAMY, CHESTNUT, BROWN, BLACK, GRAY, DARK_BROWN
      horse-style: 'WHITE_DOTS' # Stiller: NONE, WHITE, WHITEFIELD, WHITE_DOTS, BLACK_DOTS


# ------------------------------------------------------------------ #
#                       Efekt ve Ses Ayarları                        #
# ------------------------------------------------------------------ #
#
# Buradaki isimler, kullandığınız Minecraft sürümünün resmi
# materyal isimleriyle eşleşmelidir. Hatalı isimler konsolda uyarıya
# neden olur.
#
# 1.12.2 için geçerli sesler: https://helpch.at/docs/1.12.2/org/bukkit/Sound.html
# 1.12.2 için geçerli partiküller: https://helpch.at/docs/1.12.2/org/bukkit/Particle.html
#
sounds:
  countdown-start: 'ENTITY_PLAYER_LEVELUP'
  countdown-tick: 'UI_BUTTON_CLICK'
  spawn: 'ENTITY_ENDER_DRAGON_GROWL'
  hit: 'ENTITY_PLAYER_ATTACK_SWEEP'
  death: 'ENTITY_WITHER_DEATH'

effects:
  hit: 'CRIT_MAGIC'
  death: 'EXPLOSION_HUGE'


# ------------------------------------------------------------------ #
#                         Boss Bar Ayarları                          #
# ------------------------------------------------------------------ #
boss-bar:
  # Piñata için üstte çıkan can barını aktif eder veya kapatır.
  enabled: true

  # Barın rengi.
  # Seçenekler: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  color: PINK

  # Barın stili.
  # Seçenekler: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  style: SEGMENTED_20


# ------------------------------------------------------------------ #
#                         Hologram Ayarları                          #
# ------------------------------------------------------------------ #
hologram:
  # Piñata'nın üstünde DecentHolograms ile hologram gösterilmesini aktif eder/kapatır.
  enabled: true

  # Hologramın Piñata'nın ne kadar üstünde duracağını belirler (blok cinsinden).
  offset-y: 2.2


# ------------------------------------------------------------------ #
#                       Otomatik Etkinlik Sistemi                    #
# ------------------------------------------------------------------ #
#
# Sunucunuzda otomatik olarak Piñata etkinliği başlatmak için
# bu ayarları kullanabilirsiniz.
#
automatic-events:
  # Zamanlayıcıya bağlı otomatik etkinlikler.
  timed:
    # Belirli aralıklarla otomatik etkinlik başlatmayı aktif eder/kapatır.
    enabled: true

    # Etkinliğin ne sıklıkla denenmesi gerektiğini belirtir (dakika cinsinden).
    # 120 = Her 2 saatte bir kontrol eder ve şartlar uygunsa başlatır.
    interval-minutes: 120

    # Zamanlayıcı tetiklendiğinde, etkinliğin başlayabilmesi için sunucuda
    # olması gereken minimum oyuncu sayısı.
    minimum-players: 5

    # Başlatılacak Piñata'nın türü. (Yukarıdaki 'pinata-types' bölümünden bir isim)
    pinata-type: "default"

  # Sunucudaki oyuncu sayısına ulaşıldığında tetiklenen etkinlikler.
  player-count:
    # Bu özelliği aktif eder veya kapatır.
    enabled: true

    # Sunucudaki oyuncu sayısı bu değere ulaştığında etkinlik tetiklenir.
    required-players: 20

    # Bu şekilde bir etkinlik başladıktan sonra, tekrar başlayabilmesi için
    # geçmesi gereken minimum süre (dakika cinsinden). Spam'i önler.
    cooldown-minutes: 90

    # Başlatılacak Piñata'nın türü.
    pinata-type: "arena"

  # Zamanlanmış Etkinlikler (Scheduler)
  # Sunucunuz için belirli gün ve saatlerde otomatik etkinlikler planlayın.
  scheduled:
    # Bu sistemi tamamen açar veya kapatır.
    enabled: true
    # Zamanlanmış tüm etkinliklerin listesi. İstediğiniz kadar ekleyebilirsiniz.
    schedules:
      # Örnek 1: Her Cuma akşamı saat 20:00'de 'zindan' Piñata'sını başlatan bir etkinlik.
      - id: 'cuma_aksami_boss' # Her zamanlama için eşsiz bir kimlik (loglar için kullanışlı).
        enabled: true # Bu özel zamanlamayı açar veya kapatır.
        pinata-type: 'zindan'
        # Günler: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
        # Veya her gün için: 'EVERYDAY'
        day: 'FRIDAY'
        # Saat: "HH:mm" formatında (24 saatlik dilim).
        time: '20:00'
        # Etkinliğin başlayabilmesi için sunucuda olması gereken minimum oyuncu sayısı.
        minimum-players: 10
        # Etkinlik başlamadan önce yapılacak duyurular (dakika cinsinden).
        # Bu örnekte etkinlikten 15, 5 ve 1 dakika önce duyuru yapılır.
        announce-before: [ 15, 5, 1 ]

      # Örnek 2: Her gün öğleden sonra 15:30'da 'default' Piñata'sını başlatan bir etkinlik.
      - id: 'gunluk_odul_pinata'
        enabled: true
        pinata-type: 'default'
        day: 'EVERYDAY'
        time: '15:30'
        minimum-players: 5
        announce-before: [ 5, 1 ]

      # Örnek 3: Pazar günü öğlen 12:00'de başlayacak ama şu anlık kapalı olan bir etkinlik.
      - id: 'pazar_etkinligi'
        enabled: false
        pinata-type: 'pegasus'
        day: 'SUNDAY'
        time: '12:00'
        minimum-players: 15
        announce-before: [ 10, 5, 1 ]

# ------------------------------------------------------------------ #
#                    BenthPinata v1.0.0 by bentahsin                 #
# ------------------------------------------------------------------ #