name: BenthPinata
version: '1.0.0-RELEASE'
main: com.bentahsin.benthPinata.BenthPinata
api-version: '1.13'
author: bentahsin
depend:
  - DecentHolograms
softdepend:
  - TitleManager
  - PlaceholderAPI

commands:
  pinata:
    description: BenthPinata eklentisinin ana komutu.
    usage: /<command> <start|killall|reload|help>
    aliases: [pinataevent, pinyata]

permissions:
  benthpinata.admin:
    description: Eklentinin tüm komutlarına erişim sağlar.
    children:
      - benthpinata.command.start
      - benthpinata.command.killall
      - benthpinata.command.reload
      - benthpinata.command.help
      - benthpinata.command.list
      - benthpinata.command.kill
  benthpinata.command.start:
    description: /pinata start komutunu kullanma yetkisi.
    default: op
  benthpinata.command.killall:
    description: /pinata killall komutunu kullanma yetkisi.
    default: op
  benthpinata.command.reload:
    description: /pinata reload komutunu kullanma yetkisi.
    default: op
  benthpinata.command.help:
    description: /pinata help komutunu kullanma yetkisi.
    default: true
  benthpinata.command.list:
    description: /pinata list komutunu kullanma yetkisi.
    default: op
  benthpinata.command.kill:
    description: /pinata kill <ID> komutunu kullanma yetkisi.
    default: op
  benthpinata.stats.reset:
    description: Oyuncuların istatistiklerini sıfırlama yetkisi.
    default: op